name: if-cond
on:
 push:
 workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1-push
      if: github.event_name == 'push'
      run: echo "PUSH"
    - name: job2-dispatch
      if: github.event_name != 'push'
      run: echo "WORKFLOW DISPATCH"
  job2:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
    - name: job2-dispatch
      run: echo ${{ github.event_name }}