name: matrix
on: push


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [3.7, 3.8]
        os: [windows-latest, ubuntu-latest]         
    steps:
    - name: check matrix 
      run: |
        echo "${{ matrix.version }}" 
        echo "${{ matrix.os }} " 