name: var1
on: push

env:
  level: workflow 

jobs:
  get-env-1:
    runs-on: ubuntu-latest
    steps:
    - name: echo 
      run: echo "LEVEL ${{ env.level }}"
  get-env-2:
    runs-on: ubuntu-latest
    env:
      level: jobs
    steps:
    - name: echo 
      run: echo "LEVEL ${{ env.level }}"
  get-env-3:
    runs-on: ubuntu-latest 
    steps:
    - name: echo 
      env:
        level: step
      run: echo "LEVEL ${{ env.level }}"
  get-env:
    runs-on: ubuntu-latest 
    steps:
    - name: create env  
      run: echo "level=job1" >> $GITHUB_ENV 
    - name: check env  
      run: echo "LEVEL ${{ env.level }}"