name: artifact
on: push


jobs:
  upload-artifact: 
    runs-on: ubuntu-latest
    steps: 
    - name: echo 
      run: echo hello-world > hello.txt
    - name: upload artificat
      uses: actions/upload-artifact@v3
      with: 
        name: artifact-test
        path: ./hello.txt

