name: checkout-workflow
on: workflow_dispatch

jobs:
  no-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: check file list
      run: cat README.md
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: checkout acton
      uses: actions/checkout@v4
    - name: check file list 
      run: cat README.md
