name: check string
on: push

jobs:
  check1:
    runs-on: ubuntu-latest
    steps:
    - name: check start
      if: ${{ startsWith('github actions', 'git') }}
      run: echo "Starts with git"

    - name: check end
      if: ${{ endsWith('github actions', 'git') }}
      run: echo "Ends with git"

    - name: check contains
      if: ${{ contains('github actions', 'act') }}
      run: echo "Contains act"