name: Create prefixed GitHub repo and notify Slack
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name (without prefix)"
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: gh auth login 
        run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }}| gh auth login --with-token
      - name: create-repo
        run: |
          FULL_NAME="service-${{ github.event.inputs.repo_name }}" 
          gh repo create sandy-action/$FULL_NAME --public 
 