name: workflow-dispatch
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1 echo hello world
        run: echo Hello, world!
      - name: step2 echo inputs
        run: |
           echo "NAME: ${{ inputs.name }}"
           echo "ENV: ${{ inputs.environment }}"
      
