name: environment
on: push


jobs: 
  get-env:
    runs-on: ubuntu-latest
    steps:
    - name: check env & secret
      run: |
        echo "secret ${{ secrets.key }}"
        echo "variables ${{ vars.level }}"