name: if-conf
on:
 push:
 workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: job1-push
      run: echo ${{ github.event_name }}
  job2:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
    - name: job2-dispatch
      run: echo ${{ github.event_name }}